<% # Handle old behaviour of official mysql image %>
<% user = ENV.key?("MYSQL_ROOT_PASSWORD") ? "root" : ENV["MYSQL_USER"] %>
<% password = ENV.key?("MYSQL_ROOT_PASSWORD") ? ENV["MYSQL_ROOT_PASSWORD"] : ENV["MYSQL_PASSWORD"] %>
development:
  adapter: mysql2
  database: rails
  username: rails
  password: testing111
  host: localhost
  port: 3306
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  database: rails
  username: rails
  password: testing111
  host: localhost
  port: 3306
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  database: rails
  username: rails
  password: testing111
  host: localhost
  port: 3306
  socket: /var/lib/mysql/mysql.sock
